sudo: required
language: node_js
node_js:
 - "8.11.1"

services:
  - docker

before_install:
  # eventually set up AWS stuff here
  - docker-compose -f docker-compose-development.yml up -d
  - docker ps -a

install: true

script:
# Run unit tests in the app container
- docker-compose exec -T app npm run test --verbose

after_success:
# eventually wrap this in a if branch is master
- docker-compose stop
- docker-compose build --no-cache
- docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
- docker image ls
- docker tag $APP_IMAGE_NAME $DOCKER_USERNAME/$DOCKER_REPOSITORY:app_$TRAVIS_BUILD_ID
- docker tag $NGINX_IMAGE_NAME $DOCKER_USERNAME/$DOCKER_REPOSITORY:nginx_$TRAVIS_BUILD_ID
- docker push $DOCKER_USERNAME/$DOCKER_REPOSITORY:app_$TRAVIS_BUILD_ID
- docker push $DOCKER_USERNAME/$DOCKER_REPOSITORY:nginx_$TRAVIS_BUILD_ID

env:
  global:
    - APP_IMAGE_NAME=p5jswebeditor_app
    - NGINX_IMAGE_NAME=p5jswebeditor_nginx