sudo: required
language: node_js
node_js:
 - "8.11.1"

services:
  - docker

stages:
  - test
  - build

jobs:
  include:
    - stage: test
      before_install:
        - docker-compose -f docker-compose-development.yml up -d
        - docker ps -a
      install: true
      script:
      # Run unit tests in the app container
      - docker-compose exec -T app npm run test --verbose
    - stage: build
      if: branch = master OR branch = production-docker
      env:
      - APP_IMAGE_NAME=p5jswebeditor_app
      script:
      - docker-compose stop
      - docker-compose build --no-cache
      - docker image ls
      - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
      - docker tag $APP_IMAGE_NAME $DOCKER_USERNAME/$DOCKER_REPOSITORY:latest
      - docker push $DOCKER_USERNAME/$DOCKER_REPOSITORY:latest
