sudo: required
language: node_js
node_js:
 - "8.11.1"

cache:
  directories:
    - "$HOME/google-cloud-sdk/"

services:
  - docker

before_install:
  - docker-compose -f docker-compose-development.yml up -d
  - docker ps -a

install: true

script:
  - docker-compose exec -T app npm run test --verbose

after_success:
  - docker-compose stop

before_deploy:
  - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
  - source /home/travis/google-cloud-sdk/path.bash.inc
  - gcloud --quiet version
  - gcloud --quiet components update
  - gcloud --quiet components beta update
  - gcloud --quiet components update kubectl

deploy:
  - provider: script
    script: bash deploy.sh
    skip_cleanup: true
    on:
      branch: master OR production-docker

env:
  global:
    - APP_IMAGE_NAME=p5jswebeditor_app
