sudo: required
language: node_js
node_js:
 - "8.11.1"

services:
  - docker

before_install:
  # eventually set up AWS stuff here
  - docker-compose -f docker-compose-development.yml up -d
  - docker ps -a

install: true

script:
# Run unit tests in the app container
- docker-compose exec -T app npm run test --verbose

after_success:
- docker-compose stop
- docker-compose build --no-cache