version: '3.4'
services:
  mongo:
    image: mongo:3.4
    volumes:
      - dbdata:/data/db
      - "$PWD/mongo/:/docker-entrypoint-initdb.d/"
    expose:
      - "27017"
    ports:
      - '27017:27017'
    # restart: always
    # env_file:
    #   - "$PWD/.env"
  nginx:
    image: nginx:1.13
    volumes:
      - "$PWD/nginx/alpha.editor.p5js.org.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - '80:80'
    depends_on:
      - app
    links:
      - app
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    # env_file:
    #   - "$PWD/.env"
    environment:
      - MONGO_URL=mongodb://mongo:27017/p5js-web-editor
      - MONGO_HOSTNAME=mongo
      # - API_URL=https://localhost/api
      # - PORT=80
    volumes:
      - .:/opt/node/app
      - /opt/node/app/node_modules
    ports:
      - '8000:8000'
      # - '443:443'
    depends_on:
      - mongo
volumes:
  dbdata:
