version: '3.4'
services:
  mongo:
    image: mongo:3.4
    volumes:
      - dbdata:/data/db
      - "$PWD/mongo/:/docker-entrypoint-initdb.d/"
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
      - MONGO_INITDB_DATABASE
      - MONGO_RW_USERNAME
      - MONGO_RW_PASSWORD
  nginx:
    image: nginx:1.13
    volumes:
      - "$PWD/nginx/alpha.editor.p5js.org.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - '80:80'
    links:
      - app
  app:
    image: catarak/p5.js-web-editor
    environment:
      - MONGO_URL=mongodb://mongo:27017/p5js-web-editor
      - MONGO_HOSTNAME=mongo
      # - API_URL=https://localhost/api
      # - PORT=80
    volumes:
      - .:/opt/node/app
      - /opt/node/app/node_modules
    ports:
      - '8000:8000'
      # - '443:443'
    links:
      - mongo
volumes:
  dbdata:
