version: '3.4'
services:
  mongo:
    build: ./mongo
    volumes:
      - dbdata:/data/db
    expose:
      - "27017"
    # restart: always
    env_file:
      - .env
  # nginx:
  #   build: ./nginx
  #   ports:
  #     - '80:80'
  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #     target: production
  #   env_file:
  #     - .env
  #   environment:
  #     - MONGO_URL=mongodb://mongo:27017/p5js-web-editor
  #     - MONGO_HOSTNAME=mongo
  #     # - API_URL=https://localhost/api
  #     # - PORT=80
  #   volumes:
  #     - .:/opt/node/app
  #     - /opt/node/app/node_modules
  #   ports:
  #     - '8000:8000'
  #     # - '443:443'
  #     # - '80:80'
  #   depends_on:
  #     - mongo
volumes:
  dbdata:
