version: '3.4'
services:
  mongo:
    image: mongo:3.4.7
    volumes:
      - dbdata:/data/db
  server:
    build:
      context: ./
      dockerfile: Dockerfile
      target: development
    environment:
      - API_URL=/api
      - MONGO_URL=mongodb://mongo:27017/p5js-web-editor
      - PORT=8000
      - SESSION_SECRET=override_in_dotenv
      - AWS_ACCESS_KEY=override_in_dotenv
      - AWS_SECRET_KEY=override_in_dotenv
      - AWS_REGION=override_in_dotenv
      - S3_BUCKET=override_in_dotenv
      - GITHUB_ID=override_in_dotenv
      - GITHUB_SECRET=override_in_dotenv
      - MAILGUN_KEY=override_in_dotenv
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '8000:8000'
    depends_on:
      - mongo
volumes:
  dbdata:
